name: 'Build application'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    name: 'Publishing'

    strategy:
      matrix:
        system:
          - windows-latest
        platform: 
          - win-x86
          - win-x64
          - win7-x86
          - win7-x64
        config:
          - Release

    runs-on: ${{ matrix.system }}

    env:
      Project: src\CircuitCraftLab.DbLibraryManager\CircuitCraftLab.DbLibraryManager.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Publish application
        run: |
          dotnet publish $env:Project `
            --configuration ${{ matrix.config }} `
            --runtime ${{ matrix.platform }} `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeAllContentForSelfExtract=true `
            -p:EnableCompressionInSingleFile=true `
            -p:PublishReadyToRun=true `
            -p:DebugSymbols=false `
            -p:DebugType=None

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dblibrarymanager-${{ matrix.platform }}-${{ github.sha }}
          path: bin/${{ matrix.config }}/${{ matrix.platform }}/publish/
