name: 'Build application'

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-all:
    name: "Building"

    strategy:
      matrix:
        system-images: [ windows-latest ]
        platforms: [ win-x86, win-x64, win7-x86, win7-x64 ]

    runs-on: ${{ matrix.system-images }}

    env:
      Solution: DbLibraryManager.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cancel previous runs
      uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publishing application
      run: |
        dotnet publish $env:Solution -c Release -p:PublishSingleFile=true -r ${{ matrix.platforms }} --self-contained true -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRun=true -p:EnableCompressionInSingleFile=true
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish-${{ matrix.platforms }}
        path: bin/Release/${{ matrix.platforms }}/publish/
